logging: # Логирование
  level: "INFO" # Логирование в консоль
  file_level: "INFO" # Логирование в файл
  file: "var/log.logs" # Файл логирования

  format: "<green>{time:YYYY-MM-DD HH:mm}</green> | <level>{level}</level> | <level>{message}</level>" # Формат логирования
  rotation: "10 MB" # Ротация логов

update:
  start_time: "7:00 AM EVERY 7 DAYS" # Время запуска бота
  zone: "Europe/Moscow" # Часовой пояс

admin:
  username: "admin" # Логин для доступа к админ панели
  password: "admin" # Пароль для доступа к админ панели
  solt: "admin" # Соль для хеширования пароля

bot:
  admins: [12345] # Админы бота
  proxy: "http://ip:port@login:password"

user_bot:
  url: "https://t.me/example_bot"
  proxy: "http://ip:port@login:password"

api:
  frontend_port: 8000 # Порт фронтенда
  backend_port: 8080 # Порт бэкенда

  frontend_host: "0.0.0.0" # Хост фронтенда
  backend_host: "0.0.0.0" # Хост бэкенда

pdf:
  save_path: "var/pdf" # Путь сохранения PDF файлов
parsing:
  features: "html.parser"
  proxy:
    [
      "http://ip:port@login:password" # Прокси
    ]

request:
  max_concurrents: 5 # Максимальное количество одновременных HTTP-запросов
  max_retries: 5 # Максимальное количество попыток повтора для неудачных запросов
  sleep_time: 2 # Задержка в секундах между попытками повтора
  use_random: true # Включить случайные задержки, чтобы избежать обнаружения/ограничения скорости
  maxsize: 128 # Максимальный размер кэша запросов в МБ
  ttl: 300 # Время жизни кэшированных ответов в секундах (5 минут)
  max_chance: 3 # Максимальное количество попыток перед отказом
  ban_proxy: true # Включить автоматическую блокировку проблемных прокси