logging: # Логирование
  level: "INFO" # Логирование в консоль
  file_level: "INFO" # Логирование в файл
  file: "var/log.logs" # Файл логирования

  format: "<green>{time:YYYY-MM-DD HH:mm}</green> | <level>{level}</level> | <level>{message}</level>" # Формат логирования
  rotation: "10 MB" # Ротация логов

update:
  start_time: "7:00 AM" # Время запуска бота
  zone: "Asia/Yakutsk" # Часовой пояс

bot:
  api_key: "ABCDEFG:1234567890" # Токен бота
  admins: [12345] # Админы бота

database:
  db: "sqlite+aiosqlite:///var/database.db" # Строка подключения к базе данных